sudo: required
dist: trusty
language: python

python:
  - "3.5"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq -y update

install:
  - sudo apt-get install -y git
  # - sudo apt-get install -y qt5-default qtbase5-private-dev
  - sudo apt-get install -y python3-pyqt5 python3-pip
  - sudo apt-get install -y nodejs
  # - sudo apt-get install -y
  - /usr/bin/pip3 -V
  - yes | sudo /usr/bin/pip3 install qiniu sleekxmpp PyExecJS pycurl python-magic html2text

script:
  - /usr/bin/python3 tests/tests.py